# Generated by Django 6.0.3 on 2026-03-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_globalmovie_alter_movie_options_movie_global_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalmovie',
            options={'ordering': ['series_name', 'series_order', 'title']},
        ),
        migrations.AddField(
            model_name='globalmovie',
            name='series_name',
            field=models.CharField(blank=True, help_text="Nazwa serii (np. 'John Wick', 'Terminator')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='globalmovie',
            name='series_order',
            field=models.IntegerField(blank=True, help_text='Numer części w serii (1, 2, 3...)', null=True),
        ),
    ]
