# Generated by Django 6.0.3 on 2026-03-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_globalmovie_options_globalmovie_series_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watched',
            field=models.BooleanField(default=False, verbose_name='Watched'),
        ),
        migrations.AddField(
            model_name='movie',
            name='wishlist',
            field=models.BooleanField(default=False, verbose_name='On wishlist'),
        ),
    ]
