# Generated by Django 6.0.3 on 2026-03-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_watched_movie_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmovie',
            name='poster_url',
            field=models.URLField(blank=True, help_text='Link do plakatu z internetu', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, help_text='Link do plakatu z internetu', max_length=1000, null=True),
        ),
    ]
